# Generated by Django 4.2.3 on 2023-07-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_deactivateuser_user_alter_address_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeactivateUser',
        ),
    ]
