# Generated by Django 4.2.3 on 2023-07-14 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_customuser_created_at_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='mobile_number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='phone_number',
        ),
    ]
